### ISSUE TITLE
MRFT Crashes when pressing "Start"

### ISSUE THREAD

**Issue by HaiKonofanDesu** [microsoft/MixedRealityToolkit-Unity#10855]
## Describe the bug

I installed .NET 5,0 (x64) and use Windows 10 20H2
When I start the App I see the normal Start screen and can access the settings. The moment i press "Start" the app crashes. No Logs in the Error Log File

## To reproduce

1. Start App
2. Press "Start"
4. See App crasing

## Expected behavior

Getting to the next step

## Screenshots

Sadly no Screenshots as I can't screenshot a disapparing app.

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.6f1]
- MRTK Version MixedRealityFeatureTool-1.0.2206.1

## Target platform (please complete the following information)

- HoloLens 2
[MixedRealityFeatureTool.log](https://github.com/microsoft/MixedRealityToolkit-Unity/files/9298624/MixedRealityFeatureTool.log)

**Comment by HaiKonofanDesu** [comment]
Stacktrace from the Windows Event Log:

Application: MixedRealityFeatureTool.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.MixedReality.FeatureTool.Pages.SelectProjectPageViewModel..ctor(SelectProjectPage parent)
   at Microsoft.MixedReality.FeatureTool.Pages.SelectProjectPage..ctor()
   at Microsoft.MixedReality.FeatureTool.Pages.StartPage.NavigateToSelectProject()
   at Microsoft.MixedReality.FeatureTool.Pages.StartPageViewModel.Start()
   at Microsoft.MixedReality.FeatureTool.Utilities.Command.Execute(Object param)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Microsoft.MixedReality.FeatureTool.App.Main()

**Comment by HaiKonofanDesu** [comment]
After a lot of debugging:
Looks like my proxy blocked off the catalouge loading part which made the app crash. After adding every exception needed it worked again!
