### ISSUE TITLE
Mixed Reality Feature Tool crash when click start

### ISSUE THREAD

**Issue by seaweed-706** [microsoft/MixedRealityToolkit-Unity#11818]
## Describe the bug

Mixed reality feature tool does runs at first, when click "Start" button, the cursor show "Busy" for a few seconds, then the tools crash.
I've re-download, change network and change to another computer, but nothing changed. 
The tool used to work on my computer, so I'm not sure what's wrong.

## To reproduce

1. Open Mixed Reality Feature Tool
2. Click "Start"

## Expected behavior

Select a Unity project and import features

## Screenshots

![2024-03-13 143238](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/48197891/fcb32d5f-e7a6-4926-a2d9-7e4c1a6bd76e)

## Your setup 

- Unity Version: 2021.3.13
- Mixed Reality Feature Tool Version: 1.0.2209.0 Preview

## Target platform 

- HoloLens 2
- Android

## Additional context

MixedRealityFeatureTool.log
`Mixed Reality Feature Tool 1.0.2209.0
`
This is the only line in the log file.

Windows Event Log

```
Application: MixedRealityFeatureTool.exe
CoreCLR Version: 6.0.822.36306
.NET Version: 6.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.MixedReality.FeatureTool.Pages.SelectProjectPageViewModel..ctor(SelectProjectPage parent)
   at Microsoft.MixedReality.FeatureTool.Pages.SelectProjectPage..ctor()
   at Microsoft.MixedReality.FeatureTool.Pages.StartPage.NavigateToSelectProject()
   at Microsoft.MixedReality.FeatureTool.Pages.StartPageViewModel.Start()
   at Microsoft.MixedReality.FeatureTool.Utilities.Command.Execute(Object param)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Microsoft.MixedReality.FeatureTool.App.Main()

```

```
Failed application name: MixedRealityFeatureTool.exe, Version: 1.0.2209.0, Timestamp: 0x62cf00d5
Failed module name: unknown, Version: 0.0.0.0, Timestamp: 0x00000000
Exception code: 0xc0000005
Error offset: 0x000001e73b4342db
Failed process identifier: 0x5080
Failed application start time: 0x01da7510f1f4f48e
Failed application path: C:\Users\user\Desktop\MixedRealityFeatureTool.exe
Failed module path: unknown
Report identifier: d4a27d32-fbc7-440c-a0b9-82986d55af1a
Failed package full name:
Failed package-related application identifier:
```

**Comment by RobertVS-MS** [comment]
Thank you for your report...   We have been able to fix the issue with the package feed, and looks to be working now.   If you experience future problems, do please let us know.
