### ISSUE TITLE
Exception on BoundaryManager.Awake()

### ISSUE THREAD

**Issue by SabinMG** [Microsoft/MixedRealityToolkit-Unity#1209]
Any idea why its throws exception like as follows. Its only happens when you build through VS and works fine in Editor.

```
Exception: Incorrect hashcode or refCount - (GCHandleToObject)
Hash: expected 0 was 0(HashCode: 0 BlockID: 0 HandleIdInBlock: 0), RefCount: 0
(HashCode: 0 BlockID: 0 HandleIdInBlock: 0), AllocatedObjectCount: 78
MainThreadId: 4, ThisThreadId: 4
StackTrace:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at WinRTBridge.GCHandledObjects.ValidateObject(ObjectDebugInfo dbgInfo, Object o, String message)
   at WinRTBridge.GCHandledObjects.GCHandleToObject(Int64 handleId)
   at WinRTBridge.GCHandledObjects.GCHandleToPinnedArrayObject(Int64 handleId)
   at UnityEngineProxy.InternalCalls.Boundary_CUSTOM_TryGetGeometryInternalWinRT(Int32 boundaryType)
   at UnityEngine.Experimental.XR.Boundary.TryGetGeometry(List`1 geometry, Type boundaryType)
   at HoloToolkit.Unity.Boundary.BoundaryManager.CalculateBoundaryVolume()
   at HoloToolkit.Unity.Boundary.BoundaryManager.Awake()
   at HoloToolkit.Unity.Boundary.BoundaryManager.$Invoke0(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method)
Type: System.Exception
```

**Comment by 3cst4sy** [comment]
Same here. Editor works but emulator and Hololens doesnt work

**Comment by KevinKennedy** [comment]
Seeing the same thing

**Comment by keveleigh** [comment]
Known Unity bug with a fix incoming. Thanks!

**Comment by sGambolati** [comment]
Any solution or workaround at this moment?
Thanks.

**Comment by StephenHodgson** [comment]
Remove the manager
