### ISSUE TITLE
A reference to null exception in HoloToolkit\SpatialMapping\Scripts\SpatialProcessing\RemoveSurfaceVertices.cs

### ISSUE THREAD

**Issue by leimichelle** [Microsoft/MixedRealityToolkit-Unity#1850]
## Overview
line 179: int[] indices = mesh.GetTriangles(0);
causes a null reference exception

I was running in Debug mode but I can continue after the exception occurs. I wonder if this is a real issue.
I even tried to access mesh.submeshCount and that also threw a null reference exception. It seems like mesh becomes null somehow.

## Expected Behavior
pass

## Actual Behavior
NullReferenceException: 
   at UnityEngineProxy.InternalCalls.Mesh_Get_Custom_PropCanAccess(Object self)
   at UnityEngine.Mesh.CheckCanAccessSubmesh(Int32 submesh, Boolean errorAboutTriangles)
   at UnityEngine.Mesh.GetTriangles(Int32 submesh, Boolean applyBaseVertex)
   at UnityEngine.Mesh.GetTriangles(Int32 submesh)
   at HoloToolkit.Unity.SpatialMapping.RemoveSurfaceVertices.<RemoveSurfaceVerticesWithinBoundsRoutine>d__11.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

## Steps to reproduce
my project links to a bunch of other dlls so it is difficult to reproduce. But I essentially have the SpatialMapping, SpatialUnderstand and SpatialProcessing prefabs

## Unity Editor Version
2017.3.0f3 Personal

## Mixed Reality Toolkit Release Version
2017.2.1.1

**Comment by HoloLensDev** [comment]
Same problem hiere!
