### ISSUE TITLE
ARCore is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by AsWeSee** [microsoft/MixedRealityToolkit-Unity#8312]
## Describe the bug

The Android build closes immediately after launch with error in log
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.ar.core- Eb8LuRhUs4Bug9_O8JlGiA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libarcore_c.so" is 64-bit instead of 32-bit`

ARCore used from plugins, so i cant find any setting to change from 64 to 32 bit.

## To reproduce

1. Create a new app.
2. Add the MRTK Foundation.
3. Add plugins and configure the scene according to https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CrossPlatform/UsingARFoundation.html
4. Build and run on your phone

## Expected behavior

An empty scene with a camera image in the background

## Your setup (please complete the following information)

- Unity Version 2019.4.3
- MRTK Version v2.4

## Target platform (please complete the following information)

- Android

## Additional context

Logs:
```
2020.08.17 19:43:34.844 15972 16001 Info native arpresto_api.cc:133 ArPresto::ArPresto_setCameraTextureName
2020.08.17 19:43:34.844 15972 16001 Info native arpresto_api.cc:121 ArPresto::ArPresto_setConfiguration
2020.08.17 19:43:34.844 15972 16001 Info native arpresto_api.cc:145 ArPresto::ArPresto_setEnabled
2020.08.17 19:43:34.940 15972 16001 Info native arpresto_api.cc:121 ArPresto::ArPresto_setConfiguration
2020.08.17 19:43:35.070 15972 16001 Info third_party/arcore/ar/core/android/sdk/session_create.cc Entering ArSession_createWithFeatures
2020.08.17 19:43:35.073 15972 16001 Info third_party/arcore/ar/core/android/sdk/session_create.cc ARCore Version: APK version code: 202100503
2020.08.17 19:43:35.074 15972 16001 Info third_party/arcore/ar/core/android/sdk/session_create.cc ARCore Version: SDK build name: 1.9
2020.08.17 19:43:35.245 15972 16001 Info third_party/arcore/ar/core/android/sdk/session_create.cc Dynamite load ok.
2020.08.17 19:43:35.245 15972 16001 Info third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc Attempting to load native library arcore_c from package com.google.ar.core
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient   
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.ar.core-Eb8LuRhUs4Bug9_O8JlGiA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libarcore_c.so" is 64-bit instead of 32-bit
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at java.lang.System.loadLibrary(System.java:1667)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.google.vr.dynamite.NativeLibraryLoader.a(PG:32)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.google.vr.dynamite.NativeLibraryLoader.initializeAndLoadNativeLibrary(PG:14)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at fqd.a(PG:7)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at afi.onTransact(PG:5)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at android.os.Binder.transact(Binder.java:914)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.google.a.a.b.a(BaseProxy.java:10)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.google.vr.dynamite.client.b.initializeAndLoadNativeLibrary(INativeLibraryLoader.java:5)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.google.vr.dynamite.client.DynamiteClient.loadNativeRemoteLibrary(DynamiteClient.java:37)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at android.os.Handler.dispatchMessage(Handler.java:103)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at android.os.Looper.loop(Looper.java:237)
2020.08.17 19:43:35.251 15972 16001 Error DynamiteClient 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2020.08.17 19:43:35.251 15972 16001 Info third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc Dynamite::LoadNativeRemoteLibrary handle=-428404580
2020.08.17 19:43:35.251 15972 16001 Error third_party/arcore/ar/core/android/sdk/session_create.cc LoadDynamite returning AR_ERROR_FATAL.
2020.08.17 19:43:35.251 15972 16001 Error native session_manager.cc:48 ArPresto::ArCore session creation failed.
```

**Comment by AsWeSee** [comment]
The problem is not repeated in 2019.3.15. Closing the bug
